server:
  port: 8916
spring:
  cloud:
  #开启bus
    bus:
      enabled: true
  #消息中间件
#  rabbitmq:
#    host: 192.168.3.88
#    port: 5672
#    username: guest
#    password: guest
  #数据源配置
  datasource:
    #multienergy:
    #  type: com.alibaba.druid.pool.DruidDataSource
    #  driver-class-name: com.mysql.jdbc.Driver
    #  url: jdbc:mysql://192.168.3.66:3306/multienergy?characterEncoding=UTF-8&useSSL=false
    #  username: root
    #  password: admin
    #iscdev:
    #  type: com.alibaba.druid.pool.DruidDataSource
    #  driver-class-name: com.mysql.jdbc.Driver
    #  url: jdbc:mysql://192.168.3.66:3306/iscdev?characterEncoding=UTF-8&useSSL=false
    #  username: root
    #  password: admin
    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      enable: false

#swagger设置
thpower:
  swagger:
    open: true
    title: 多能协同网络能量流分布分析
    description: 多能协同网络能量流分布分析后台微服务
  pagination:
    pageSize: 20  #分页设置
  #权限设置
  oauth2:
    open: false
#mybatis
mybatis:
  type-aliases-package:  com.thpower.anaflow
  config-location: classpath:mybatis.xml
#开启断路器
feign:
  hystrix:
    enabled: true
#配置刷新端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
    #org.springframework.jdbc.datasource: debug
    #org.springframework.security : debug
    #com.thpower: TRACE
