server:
  port: 8919
spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${thpower.database.url}/dnxt_analyze?characterEncoding=UTF-8&useSSL=false
    username: ${thpower.database.username}
    password: ${thpower.database.password}
    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50

#swagger设置
thpower:
  swagger:
    open: true
    title: 能源质量分析
    description: 能源质量分析后台微服务
  pagination:
    pageSize: 20  #分页设置
  #权限设置
  oauth2:
    open: false
#mybatis
mybatis:
  type-aliases-package:  com.thpower.anaquality
  config-location: classpath:mybatis.xml
#开启断路器
feign:
  hystrix:
    enabled: true
#配置刷新端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
    #org.springframework.jdbc.datasource: debug
    #org.springframework.security : debug
    #com.thpower: TRACE
