server:
  port: 9030
management:
  security:
    enabled: false
thpower:
  user:
    userName: zhoujundongConsumer0005
  swagger:
    open: true
    title: 消费者服务接口文档
    description: 测试程序
spring:
  zipkin:
    base-url: http://192.168.3.88:9001
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1  #收集的百分比，1 = 100%，默认0.1 = 10%