server:
  port: 9020
spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://120.92.89.125:33061/energyanalysis?characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: admin
    url: jdbc:mysql://${thpower.database.url}/energyanalysis-gt?characterEncoding=UTF-8&useSSL=false
    username: ${thpower.database.username}
    password: ${thpower.database.password}
    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      #enable: false

#swagger设置
thpower:
  swagger:
    open: true
    title: 企业能效管理-钢铁行业
    description: 企业能效管理钢铁行业后台微服务
  pagination:
    pageSize: 20  #分页设置
  #权限设置
  oauth2:
    open: false
#mybatis
mybatis:
  type-aliases-package:  com.thpower.energyanalysis
  config-location: classpath:mybatis.xml
#开启断路器
feign:
  hystrix:
    enabled: true
#配置刷新端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
