server:
  port: 9029

spring:
  #数据源配置
  datasource1:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #jeesite
    url: jdbc:mysql://${thpower.database.url}/hnyw?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${thpower.database.username}
    password: ${thpower.database.password}
    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
  datasource2:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #jeesite
    url: jdbc:mysql://192.168.100.133:3306/hisdb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50

#swagger设置
thpower:
  swagger:
    open: true
    title: 运维管理
    description: 运维管理后台微服务
  pagination:
    pageSize: 20  #分页设置
  #权限设置
  oauth2:
    open: false
#mybatis
mybatis:
  type-aliases-package: com.thpower.thpoweroperation.entity
  config-location: classpath:mybatis.xml
#开启断路器
feign:
  hystrix:
    enabled: true
#配置刷新端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#历史数据统计服务 225济南测试地址  90公网测试地址   90:30009正式地址  30037历史告警服务
#hisUrl: http://192.168.2.225:9006
#hisUrl: http://113.128.186.90:9006
#hisUrl: http://113.128.186.90:30009
hisUrl: http://192.168.100.131:30010
hisAlarmUrl: http://192.168.100.131:30037
#资产框架地址
assetUrl: http://192.168.100.131:30021/
