server:
  port: 9034

spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #jeesite
    url: jdbc:mysql://${thpower.database.url}/savingdb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456


    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50


#swagger设置
thpower:
  swagger:
    open: true
    title: 节能管理
    description: 节能管理后台微服务
  pagination:
    pageSize: 20  #分页设置
  #权限设置
  oauth2:
    open: false
#mybatis
mybatis:
  type-aliases-package:  com.thpower.saving
  config-location: classpath:mybatis.xml
#开启断路器
feign:
  hystrix:
    enabled: true
#配置刷新端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
