server:
  port: 8085

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #jeesite
    url: jdbc:mysql://${thpower.database.url}/thpcloud?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50

#swagger设置
thpower:
  swagger:
    open: true
    title: scada
    description: scada服务
  pagination:
    pageSize: 20  #分页设置

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml           #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package:  com.thpower.scada.model
  config-location: classpath:mybatis.xml

feign:
  httpclient:
    enable: true
  hystrix:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"  #配置刷新端点