thpower:
  database:
    url: 192.168.100.183:3306
    username: root
    password: 123456
  keyue-auth:
    open: true
    url: 192.168.11.49:8802/uap/token/v1
  servername:
    # -v1.0
    producer: thpower-producer-v1.0.0

    consumer: thpower-consumer-v1.0.0

    dnxtDer: csg-dnxt-der-v1.0.0

    analyze: csg-dnxt-analyze-v1.0.0

    common: csg-dnxt-common-v1.0.0

    scada: csg-dnxt-scada-v1.0.0

#链路跟踪服务器
spring:
  zipkin:
    base-url: http://192.168.11.46:9001
  sleuth:
    sampler:
      probability: 1  #收集的百分比，1 = 100%，默认0.1 = 10%

#外部系统定义
out:
  userInfourl: ${userInfourl:http://192.168.100.181:30023/userInfo}
  #物联-历史库
  archiveurl: ${archiveurl:http://192.168.100.181:30009/api/arch}
  #物联-实时库
  snapurl: ${snapurl:http://192.168.100.181:30003/api/snap}
  #资产框架
  asseturl: ${asseturl:http://192.168.100.181:30021/THPISC/api}
  #微网设备控制（物联网平台）
  microgridurl: ${microgridurl:http://192.168.100.181:30038/}
  #预测
  prediction: ${microgridurl:http://192.168.100.181:9999/}

#运维管理url
url:
  operation: ${operation:http://192.168.100.181:30057/v1.0.0/thpower-operation}