server:
  port: 9029

spring:
  #数据源配置
  datasource1:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #jeesite
    url: jdbc:mysql://${thpower.database.url}/hnyw?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${thpower.database.username}
    password: ${thpower.database.password}

    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50


#swagger设置
thpower:
  swagger:
    open: true
    title: 运维管理
    description: 运维管理后台微服务
  pagination:
    pageSize: 20  #分页设置
  #权限设置
  oauth2:
    open: false
#mybatis
mybatis:
  type-aliases-package:  com.thpower.thpoweroperation
  config-location: classpath:mybatis.xml
#开启断路器
feign:
  hystrix:
    enabled: true
#配置刷新端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#历史服务接口
hisUrl: ${hisUrlInfo:http://192.168.100.131:30009}
#实时服务接口
snapUrl: ${snapUrlInfo:http://192.168.100.131:30003}
#查询测点信息
tagInfoUrl: ${tagInfoUrlInfo:http://192.168.100.131:30005}
#历史告警
hisAlarmUrl: ${hisAlarmUrlInfo:http://192.168.100.131:30037}
#设备信息
hisDvUrl: ${hisDvUrlInfo:http://192.168.100.131:30038}
#资产框架地址
assetUrl: ${assetUrlInfo:http://192.168.100.131:30021/}