server:
  port: 9008
spring:
  cloud:
  #开启bus
    bus:
      enabled: true
  #消息中间件
  rabbitmq:
    host: 192.168.3.88
    port: 5672
    username: guest
    password: guest
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.66:3306/multienergy?characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
    #druid连接池管理
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
#swagger设置
thpower:
  swagger:
    open: true
    title: 微服务例子
    description: 东东编写的微服务
  pagination:
    pageSize: 20  #分页设置
#mybatis
mybatis:
  type-aliases-package:  com.thpower.sample
  config-location: classpath:mybatis.xml
#开启断路器
feign:
  hystrix:
    enabled: true
#配置刷新端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#logging.level.com.bjgk.historyData.dao=TRACE
#logging:
#  level:
#    com:
#      thpower:
#        TRACE
