server:
  port: 8933
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.133:3306/dnxt_cmn?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#swagger设置
thpower:
  swagger:
    open: true
    title: 定时任务管理
    description: 分布式定时任务
  pagination:
    pageSize: 20  #分页设置
#mybatis
mybatis:
  type-aliases-package:  com.thpower.timertask
  config-location: classpath:mybatis.xml

feign:
  httpclient:
    enable: true
  hystrix:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"  #配置刷新端点